[package]
name = "binspect"
description = "A simple inspector tool to inspect several types of binaries."
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
thiserror = "2.0.18"
lief = { git = "https://github.com/lief-project/LIEF.git" } #TODO: use version of LIEF
colored = "3.1.1"
